-- Floorplan geometry additions
ALTER TABLE "Venue"
  ADD COLUMN IF NOT EXISTS "floorplanRoomWidth" INTEGER DEFAULT 1200,
  ADD COLUMN IF NOT EXISTS "floorplanRoomHeight" INTEGER DEFAULT 800,
  ADD COLUMN IF NOT EXISTS "floorplanGridSize" INTEGER DEFAULT 20;

ALTER TABLE "Table"
  ADD COLUMN IF NOT EXISTS "angle" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "shape" TEXT,
  ADD COLUMN IF NOT EXISTS "w" INTEGER DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "h" INTEGER DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "minSeating" INTEGER DEFAULT 1;

ALTER TABLE "Table" ALTER COLUMN "x" SET DEFAULT 0;
ALTER TABLE "Table" ALTER COLUMN "y" SET DEFAULT 0;
